### ISSUE TITLE
库存操作是否会有并发问题

### ISSUE THREAD

**Issue by Madao1994** [lilishop/lilishop#122]
我看到库存扣减那里的逻辑，sku的库存扣减是通过lua脚本操作Redis实现的，这里没有疑问，但是 初始化redis库存以及库存数据回写到数据库的时候是没有加锁的，这里是否存在并发问题？

**Comment by lilishop** [comment]
redis 操作后会同步数据库。存在极端情况下，库存不匹配的问题。但是普通的兵法不会导致
